# Generated by Django 5.0.7 on 2024-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
