# Generated by Django 5.0.7 on 2024-07-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0002_alter_interest_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='interest',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
