# Generated by Django 5.0.7 on 2024-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0003_rename_timestamp_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='accepted',
            field=models.BooleanField(blank=True, choices=[(True, 'Accepted'), (False, 'Not Accepted')], default=False, null=True),
        ),
    ]
