# Generated by Django 5.0.7 on 2024-07-24 04:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0004_alter_interest_accepted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('sender', 'recipient')},
        ),
    ]
